### PR TITLE
Update for newest windows version

### PR DESCRIPTION
**Pull request by kaimu-kun**

### CODE REVIEW

**Comment by Metick** [comment]
hi, can you make it actually so the offset is used for which version that is? rather than modifying the offset directly and just assume everyone is on that version.

**Comment by kaimu-kun** [comment]
Hey, sure, I can take a look at it. I checked the Windows version, and the int was the same. There might be a change in Ubr tho.

**Comment by Metick** [comment]
It's most likely a change in ubr

**Comment by kaimu-kun** [comment]
done

**Comment by Metick** [comment]
Thanks!

**Pull request merged**
